### ISSUE TITLE
The extension was removed from Chrome Web Store

### ISSUE THREAD

**Issue by jeremias8** [nralbrecht/youtube-hide-controls#12]
**_This extension violates the Chrome Web Store policy._**

Could you provide the `.zip` for Chrome in the Releases?

How to install: https://itigic.com/install-crx-extensions-from-outside-the-chrome-store/

**Comment by nralbrecht** [comment]
Unfortunately the extension was removed do to a YouTube trademark violation. The message i got from them was pretty vague i have to figure out what exactly they have a problem with. But if i fix the problem the extension will be available again.

I will add the zip to the latest release.

**Comment by aminya** [comment]
Not only that. I have started receiving messages that this extension contains malware!

**Comment by nralbrecht** [comment]
I am currently in the process of getting it approved. It will likely take a bit longer still.

You get shown the message above because due to the removal from the store they no longer vouch for the safety of the extension. For now the work around for when you are not allowed to enable the original one, is to install the extension by dragging the [youtube-hide-controls_chrome_2.6.0.zip](https://github.com/nralbrecht/youtube-hide-controls/releases/download/v2.6.0/youtube-hide-controls_chrome_2.6.0.zip) from the [last release](https://github.com/nralbrecht/youtube-hide-controls/releases/tag/v2.6.0) into the [Google Chrome extension page](chrome://extensions/)

**Comment by nralbrecht** [comment]
After a long wait the extension is now finally available on the Chrome Web Store again. Version 2.6.1 is now live for both Chrome and Firefox.
