### ISSUE TITLE
v3.0.2 in conflict with volume scroll feature of Enhancer for YouTube

### ISSUE THREAD

**Issue by shukrifathil** [nralbrecht/youtube-hide-controls#16]
With this version, I am unable to use the mouse scrollwheel to control volume (feature provided bv Enhancer for YouTube) at first. However, I can control the volume once the video is in fullscreen and once it exits out of the fullscreen. 

I rolled back to v.3.0.1 and everything works as normal.

**Comment by nralbrecht** [comment]
That's weird as v3.0.2 only changed default settings value. I will have a look.

**Comment by dkaknbk** [comment]
I don't have the exact same issue, but the newest update made it so that the controls disappear completely in non-fullscreen mode even though I enabled fullscreen only until I go into fullscreen mode once and return to non-fullscreen mode, which fixes it exactly like OP's issue, so I think it might be related.

**Comment by nralbrecht** [comment]
Thank's @dkaknbk for the pointer. It looks like the addon thinks the YouTube page is in fullscreen on page load.

**Comment by nralbrecht** [comment]
I fixed a race condition that caused the add-on to always think that YouTube is in the fullscreen mode. It will be part of v3.0.3 that is currently in the process of being validated and released.

@shukrifathil If your issue still persists after the update, feel free to reopen this issue.

**Comment by shukrifathil** [comment]
Seems to work as usual now. Thanks for the fix.
